services:

  minecraft:
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    profiles:
      - minecraft
    ports:
      - "25565:25565"
    volumes:
      - ./data/server:/data
    env_file:
      - minecraft.env

  bluemap:
    image: ghcr.io/bluemap-minecraft/bluemap:latest
    restart: unless-stopped
    command: -r -u -w
    profiles:
      - minecraft
    depends_on:
      - minecraft
    ports:
      - '8100:8100'
    volumes:
      - './config/bluemap/core.conf:/app/config/core.conf:ro'
      - './data/bluemap/config:/app/config'
      - './data/bluemap/web:/app/web'
      - './data/bluemap/data:/app/data'
      - './data/server/world:/app/world'
  
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/portainer:/data
    ports:
      - 9000:9000

  nginx:
    image: nginx:latest
    restart: unless-stopped
    profiles:
      - no-ssl
    depends_on:
      - bluemap
      - portainer
    ports:
      - '80:80'
    volumes:
      - ./config/nginx:/etc/nginx/conf.d/:ro
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  nginx-ssl:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - nginx
    profiles:
      - ssl
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./config/nginx:/etc/nginx/conf.d/:ro
      - ./data/nginx/nginx.ssl.conf:/etc/nginx/nginx.conf:ro
      - ./data/letsencrypt:/etc/letsencrypt

  new-ssl-certificate:
    image: certbot/certbot:latest
    restart: no
    network_mode: host
    profiles:
      - new-ssl-certificate
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
    command: >
      certonly --standalone
        --preferred-challenges http
        -d ${DOMAIN_NAME}
        --email ${DOMAIN_ADMIN_EMAIL}
        --agree-tos
        --non-interactive
