services:

  minecraft:
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    profiles:
      - minecraft
    ports:
      - "25565:25565"
    volumes:
      - ./data/server:/data
    environment:
      EULA: TRUE

      SERVER_NAME: Mine dos Crazy
      MOTD: "Owwwwwwwww §aStoneMask§r..."
      ICON: https://i.scdn.co/image/ab67616d0000b27332ff042034155f8757459ddb

      VERSION: 1.21.8
      ONLINE_MODE: false
      MAX_PLAYERS: 12
      ENABLE_COMMAND_BLOCK: false
      DIFFICULTY: normal
      PVP: true
      MODE: survival
      LEVEL_TYPE: minecraft:default
      SPAWN_NPCS: true
      SPAWN_ANIMALS: true
      SPAWN_MONSTERS: true
      GENERATE_STRUCTURES: true
      ALLOW_NETHER: true
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ALLOW_FLIGHT: false
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 4

      ENABLE_RCON: true
      RCON_PORT: 25575
      RCON_PASSWORD: "minedoscrazy"

      MEMORY: 8G
      MAX_MEMORY: 12G
      JVM_XX_OPTS: "-XX:+UseG1GC -XX:ParallelGCThreads=8 -XX:MaxGCPauseMillis=200"

      TYPE: FABRIC
      FABRIC_FORCE_REINSTALL: false
      MODRINTH_ALLOWED_VERSION_TYPE: beta
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_PROJECTS: |
        fabric-api
        lithium
        cloth-config
        balm
        inventory-management

  rcon:
    image: itzg/rcon:latest
    restart: unless-stopped
    profiles:
      - minecraft
    depends_on:
      - minecraft
    ports:
      - "4326:4326"
      - "4327:4327"
    environment:
      RWA_USERNAME: ${RCON_ADMIN_USERNAME:-admin}
      RWA_PASSWORD: ${RCON_ADMIN_PASSWORD:-admin}
      RWA_ADMIN: "TRUE"
      RWA_RCON_HOST: minecraft
      RWA_RCON_PASSWORD: "minedoscrazy"
      RWA_WEBSOCKET_URL_SSL: "wss://${DOMAIN_NAME}:4327"
      RWA_WEBSOCKET_URL: "ws://${DOMAIN_NAME}:4327"

  bluemap:
    image: ghcr.io/bluemap-minecraft/bluemap:latest
    restart: unless-stopped
    command: -r -u -w
    profiles:
      - minecraft
    depends_on:
      - minecraft
    volumes:
      - './config/bluemap/core.conf:/app/config/core.conf:ro'
      - './data/bluemap/config:/app/config'
      - './data/bluemap/web:/app/web'
      - './data/bluemap/data:/app/data'
      - './data/server/world:/app/world'
  
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    profiles:
      - minecraft
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/portainer:/data

  nginx:
    image: nginx:latest
    restart: unless-stopped
    profiles:
      - no-ssl
    depends_on:
      - bluemap
      - portainer
    ports:
      - '80:80'
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf:/etc/nginx/conf.d/:ro
      - ./config/nginx/www:/var/www/html

  nginx-ssl:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - bluemap
      - portainer
    profiles:
      - ssl
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data/nginx/nginx.ssl.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf:/etc/nginx/conf.d/:ro
      - ./config/nginx/www:/var/www/html:ro
      - ./data/letsencrypt:/etc/letsencrypt

  new-ssl-certificate:
    image: certbot/certbot:latest
    restart: no
    network_mode: host
    profiles:
      - new-ssl-certificate
    volumes:
      - ./config/nginx/www:/var/www/html
      - ./data/letsencrypt:/etc/letsencrypt
      - ./logs/letsencrypt:/var/log/letsencrypt
    command: >
      certonly --webroot
        --preferred-challenges http
        -d ${DOMAIN_NAME}
        --http-01-address 0.0.0.0
        --email ${DOMAIN_ADMIN_EMAIL}
        --webroot-path /var/www/html
        --agree-tos
        --non-interactive
        --verbose
