services:

  certbot:
    image: certbot/certbot:latest
    restart: no
    network_mode: host
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
    command: >
      certonly --standalone
        --preferred-challenges http
        -d minedoscrazy.the.br
        --email jjpaulo2@protonmail.com
        --agree-tos
        --non-interactive
