services:

  certbot:
    image: certbot/certbot:latest
    restart: no
    network_mode: host
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
    command: >
      certonly --standalone \
        -d minedoscrazy.the.br \
        --email jjpaulo2@protonmail.com \
        --preferred-challenges http \
        --agree-tos \
        --non-interactive
