services:

  minecraft:
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data

    environment:
      EULA: TRUE

      SERVER_NAME: Mine dos Crazy
      MOTD: "Owwwwwwwww §aStoneMask§r..."
      ICON: https://i.scdn.co/image/ab67616d0000b27332ff042034155f8757459ddb

      VERSION: 1.21.8
      ONLINE_MODE: false
      TYPE: PAPER
      MAX_PLAYERS: 20
      ENABLE_COMMAND_BLOCK: false
      DIFFICULTY: normal
      PVP: true
      MODE: survival
      LEVEL_TYPE: minecraft:default
      SPAWN_NPCS: true
      SPAWN_ANIMALS: true
      SPAWN_MONSTERS: true
      GENERATE_STRUCTURES: true
      ALLOW_NETHER: true
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      ALLOW_FLIGHT: false
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 4
      
      MEMORY: 10G
      JVM_XX_OPTS: "-XX:+UseG1GC -XX:ParallelGCThreads=8 -XX:MaxGCPauseMillis=200"