server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    timeout: 10s
    external_labels:
      cluster: ${COMPOSE_PROJECT_NAME}

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: container
        replacement: '$1'

      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service

      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: project
        
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream

      - source_labels: ['__meta_docker_container_id']
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/*-json.log

      - source_labels: ['__meta_docker_container_name']
        regex: '/(loki|promtail)$'
        action: drop
