server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Caminho do log do container
      - source_labels: ['__meta_docker_container_id']
        target_label: '__path__'
        replacement: /var/lib/docker/containers/$1/*.log

      # Nome legível do container (remove a / inicial)
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        replacement: '$1'
        target_label: container

      # Imagem usada
      - source_labels: ['__meta_docker_container_image']
        target_label: image

      # Labels do Docker Compose (se estiver usando docker compose)
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: service
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: project
      - source_labels: ['__meta_docker_container_label_com_docker_compose_container_number']
        target_label: compose_number

      # Compatibilidade entre as labels de serviço
      - source_labels: [service]
        target_label: service_name