apiVersion: 1
datasources:

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Prometheus / minedoscrazy
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false

  - name: Loki / minedoscrazy
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true