global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "node-prometheus-exporter"
    static_configs:
      - targets: ["node-prometheus-exporter:9100"]

  - job_name: "minecraft-prometheus-exporter"
    static_configs:
      - targets: ["minecraft-prometheus-exporter:9150"]
