http:
  services:
    portainer:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://portainer:9000"

    bluemap:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://bluemap:8100"

    grafana:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://grafana:3000"

  middlewares:
    bluemap-dynamic:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
          names: minedoscrazy-bluemap
          dynamic:
            displayName: Bluemap
            refreshFrequency: 15s
            showDetails: true
            theme: ghost

    grafana-dynamic:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
          names: minedoscrazy-grafana
          dynamic:
            displayName: Grafana
            refreshFrequency: 15s
            showDetails: true
            theme: ghost

    portainer-dynamic:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
          names: minedoscrazy-portainer
          dynamic:
            displayName: Portainer
            refreshFrequency: 15s
            showDetails: true
            theme: ghost

  routers:
    map:
      rule: Host(`map.{{ env "DOMAIN_NAME" }}`)
      entryPoints: ["web", "websecure"]
      middlewares: ["bluemap-dynamic@file"]
      service: "bluemap"
      tls:
        certResolver: letsencrypt
    
    admin:
      rule: Host(`admin.{{ env "DOMAIN_NAME" }}`)
      entryPoints: ["web", "websecure"]
      middlewares: ["portainer-dynamic@file"]
      service: "portainer"
      tls:
        certResolver: letsencrypt

    monitoring:
      rule: Host(`monitoring.{{ env "DOMAIN_NAME" }}`)
      entryPoints: ["web", "websecure"]
      middlewares: ["grafana-dynamic@file"]
      service: "grafana"
      tls:
        certResolver: letsencrypt
