http:
  services:
    portainer:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://portainer:9000"

    bluemap:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://bluemap:8100"

    grafana:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://grafana:3000"

    rcon:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://rcon:4326"

    rcon-ws:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://rcon:4327"

  middlewares:
    bluemap-dynamic:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
          names: minedoscrazy-bluemap
          dynamic:
            displayName: Bluemap
            refreshFrequency: 15s
            showDetails: true
            theme: ghost

    grafana-dynamic:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
          names: minedoscrazy-grafana
          dynamic:
            displayName: Grafana
            refreshFrequency: 15s
            showDetails: true
            theme: ghost

    portainer-dynamic:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
          names: minedoscrazy-portainer
          dynamic:
            displayName: Portainer
            refreshFrequency: 15s
            showDetails: true
            theme: ghost
    
    rcon-dynamic:
      plugin:
        sablier:
          sablierUrl: http://sablier:10000
          sessionDuration: 1m
          names: minedoscrazy-rcon
          dynamic:
            displayName: RCON Web Admin
            refreshFrequency: 15s
            showDetails: true
            theme: ghost
    
    route-strip:
      stripPrefix:
        prefixes:
          - "/ws/"

  routers:
    map:
      rule: Host(`map.{{ env "DOMAIN_NAME" }}`)
      entryPoints: ["web", "websecure"]
      middlewares: ["bluemap-dynamic@file"]
      service: "bluemap"
      tls:
        certResolver: letsencrypt
    
    admin:
      rule: Host(`admin.{{ env "DOMAIN_NAME" }}`)
      entryPoints: ["web", "websecure"]
      middlewares: ["portainer-dynamic@file"]
      service: "portainer"
      tls:
        certResolver: letsencrypt

    monitoring:
      rule: Host(`monitoring.{{ env "DOMAIN_NAME" }}`)
      entryPoints: ["web", "websecure"]
      middlewares: ["grafana-dynamic@file"]
      service: "grafana"
      tls:
        certResolver: letsencrypt

    rcon:
      rule: Host(`rcon.{{ env "DOMAIN_NAME" }}`)
      entryPoints: ["web", "websecure"]
      middlewares: ["rcon-dynamic@file"]
      service: "rcon"
      tls:
        certResolver: letsencrypt

    rcon-ws:
      rule: Host(`rcon.{{ env "DOMAIN_NAME" }}`) && PathPrefix(`/ws/`)
      entryPoints: ["web", "websecure"]
      middlewares: ["rcon-dynamic@file", "route-strip@file"]
      service: "rcon-ws"
      tls:
        certResolver: letsencrypt
