api:
  dashboard: false
  insecure: false

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":8082"

providers:
  docker: {}
  file:
    filename: /etc/traefik/dynamic-config.yml

experimental:
  plugins:
    sablier:
      moduleName: "github.com/sablierapp/sablier"
      version: "v1.10.1"

metrics:
  prometheus:
    entryPoint: "metrics"
    addEntryPointsLabels: true
    addServicesLabels: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "{{ env 'DOMAIN_ADMIN_EMAIL' }}"
      storage: acme.json
      httpChallenge:
        entryPoint: web

logs:
  general:
    level: DEBUG