services:

  download-mods:
    image: ghcr.io/jjpaulo2/games-servers/base:latest
    restart: no
    pull_policy: always

    volumes:
      - ./scripts:/srv/scripts
      - mods:/srv/download

    environment:
      MINECRAFT_VERSION: ${MINECRAFT_VERSION}
      MOD_LOADER: "${MOD_LOADER:-fabric}"
      MODS: |
        fabric-api
        xaeros-minimap
        sodium
        sodium-extra
        modmenu
        lithium
        inventory-management
        immediatelyfast
        ferrite-core
        entityculling

    command: bash scripts/download-mods.sh


volumes:
  mods:
