---
- name: Atualizar servidor
  become: false
  hosts: minedoscrazy

  vars:
    app_dir: minedoscrazy
    repo_url: https://github.com/jjpaulo2/minedoscrazy.git

  vars_prompt:
    - name: "domain_name"
      prompt: "Nome do domínio do servidor"
      private: yes

    - name: "domain_admin_email"
      prompt: "Email do administrador do domínio"
      private: yes

    - name: "rcon_admin_password"
      prompt: "Senha do administrador RCON"
      private: yes

  tasks:
    - name: Derrubar o Docker Compose
      ansible.builtin.shell: make stop-server
      args:
        chdir: "{{ app_dir }}"

    - name: Garantir permissões do diretório de configuração
      become: true
      ansible.builtin.file:
        path: "{{ app_dir }}/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: true
        state: directory

    - name: Atualizar repositório com git pull
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        update: true
        force: true

    - name: Preparar os arquivos do server
      become: true
      ansible.builtin.shell: make files

    - name: Subir os containers com Docker Compose
      ansible.builtin.shell: make serve
      args:
        chdir: "{{ app_dir }}"
      environment:
        DOMAIN_NAME: "{{ domain_name }}"
        DOMAIN_ADMIN_EMAIL: "{{ domain_admin_email }}"
        RCON_PASSWORD: "{{ rcon_admin_password }}"
