---
- name: Atualizar servidor
  become: false
  hosts: minedoscrazy

  vars:
    app_dir: minedoscrazy
    repo_url: https://github.com/jjpaulo2/minedoscrazy.git

  vars_prompt:
    - name: "domain_name"
      prompt: "Nome do domínio do servidor"
      private: yes

    - name: "rcon_admin_username"
      prompt: "Nome de usuário do administrador RCON"
      private: yes

    - name: "rcon_admin_password"
      prompt: "Senha do administrador RCON"
      private: yes

  tasks:
    - name: Derrubar o Docker Compose
      ansible.builtin.shell: make stop-server
      args:
        chdir: "{{ app_dir }}"

    - name: Atualizar repositório com git pull
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        update: true
        force: true

    - name: Subir os containers com Docker Compose
      ansible.builtin.shell: make serve-ssl
      args:
        chdir: "{{ app_dir }}"
      environment:
        DOMAIN_NAME: "{{ domain_name }}"
        RCON_ADMIN_USERNAME: "{{ rcon_admin_username }}"
        RCON_ADMIN_PASSWORD: "{{ rcon_admin_password }}"
