---
- name: Atualizar servidor
  become: false
  hosts: minedoscrazy

  vars:
    app_dir: minedoscrazy
    repo_url: https://github.com/jjpaulo2/minedoscrazy.git

  tasks:
  
    - name: Derrubar o Docker Compose
      ansible.builtin.shell: make stop-server
      args:
        chdir: "{{ app_dir }}"

    - name: Atualizar repositório com git pull
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        update: true
        force: true

    - name: Subir os containers com Docker Compose
      ansible.builtin.shell: make serve-ssl
      args:
        chdir: "{{ app_dir }}"
