---
- name: Restaurar backup dos dados do servidor
  become: false
  hosts: minedoscrazy

  vars:
    app_dir: minedoscrazy
    app_timezone: America/Sao_Paulo

  vars_prompt:
    - name: "s3_bucket"
      prompt: "Bucket S3 onde o backup será armazenado"
      private: true

    - name: "backup_file"
      prompt: "Nome do arquivo de backup que você deseja restaurar"
      private: false

  tasks:    
    - name: Derrubar o Docker Compose
      ansible.builtin.shell: make stop-server
      args:
        chdir: "{{ app_dir }}"

    - name: Criar backup dos dados
      block:

      - name: Baixar backup do S3
        amazon.aws.aws_s3:
          bucket: "{{ s3_bucket }}"
          object: "{{ backup_file }}"
          dest: "{{ app_dir }}/{{ backup_file }}"
          mode: get
      
      - name: Limpar save atual
        become: true
        ansible.builtin.file:
          path: "{{ app_dir }}/data/minecraft/world"
          state: absent

      - name: Descompactar o ZIP na pasta
        become: true
        ansible.builtin.unarchive:
          src: "{{ app_dir }}/{{ backup_file }}"
          dest: "{{ app_dir }}/data/minecraft"
          remote_src: true
      
      - name: Ajustar dono do mundo
        become: true
        ansible.builtin.command: "sudo chown -R 1000:1000 {{ app_dir }}/data/minecraft/world"

      - name: Subir os containers com Docker Compose
        ansible.builtin.shell: make serve-ssl
        args:
          chdir: "{{ app_dir }}"
        environment:
          DOMAIN_NAME: "{{ domain_name }}"
          RCON_ADMIN_USERNAME: "{{ rcon_admin_username }}"
          RCON_ADMIN_PASSWORD: "{{ rcon_admin_password }}"
          
      always:
        - name: Remover arquivo do backup
          ansible.builtin.file:
            path: "{{ app_dir }}/{{ backup_file }}"
            state: absent
        
