name: Desligar Servidor na AWS
description: Este workflow desliga uma instância EC2 quando acionado manualmente.

on:
  workflow_dispatch:
    inputs:
      confirmation:
        type: boolean
        description: Tem certeza que deseja desligar o servidor?
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stop-server:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirmation
    environment: aws

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Stop EC2 Instance
        run: |
          aws ec2 stop-instances --instance-ids ${{ secrets.AWS_INSTANCE_ID }}